"""create-admin-file

Revision ID: 068f1b1dd374
Revises: 47349d7092be
Create Date: 2023-05-22 12:04:25.620901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '068f1b1dd374'
down_revision = '47349d7092be'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_email', sa.String(), nullable=True),
    sa.Column('admin_username', sa.String(), nullable=True),
    sa.Column('admin_password', sa.String(), nullable=True),
    sa.Column('admin_price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin')
    # ### end Alembic commands ###
