"""

Revision ID: 47349d7092be
Revises: 1ceed5e99a02
Create Date: 2023-05-22 11:09:54.876536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47349d7092be'
down_revision = '1ceed5e99a02'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
