"""add-new-type

Revision ID: 4ff5615c9491
Revises: fed2004d195c
Create Date: 2023-05-22 14:32:02.889869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ff5615c9491'
down_revision = 'fed2004d195c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_email', sa.String(), nullable=True),
    sa.Column('admin_username', sa.String(), nullable=True),
    sa.Column('admin_password', sa.String(), nullable=True),
    sa.Column('admin_price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tokens', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('price', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('admin')
    # ### end Alembic commands ###
