"""

Revision ID: fed2004d195c
Revises: 068f1b1dd374
Create Date: 2023-05-22 13:32:36.783244

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'fed2004d195c'
down_revision = '068f1b1dd374'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_email', sa.String(), nullable=True),
    sa.Column('admin_username', sa.String(), nullable=True),
    sa.Column('admin_password', sa.String(), nullable=True),
    sa.Column('admin_price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sqlalchemy_utils.types.email.EmailType(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tokens', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('price', sa.Numeric(precision=9, scale=4), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('admin')
    # ### end Alembic commands ###
