"""add usdt price

Revision ID: 862e8e059ca7
Revises: 17db1359ea1f
Create Date: 2023-06-20 23:13:48.734896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "862e8e059ca7"
down_revision = "17db1359ea1f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("admins", sa.Column("usdt_price", sa.Numeric(), nullable=True))
    op.create_unique_constraint(None, "admins", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "admins", type_="unique")
    op.drop_column("admins", "usdt_price")
    # ### end Alembic commands ###
