"""add total price

Revision ID: 86b01995ce51
Revises: b926f1356a75
Create Date: 2023-07-06 19:53:30.930526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "86b01995ce51"
down_revision = "b926f1356a75"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("total_price", sa.Numeric(precision=9, scale=6), nullable=True),
    )
    op.alter_column(
        "users",
        "tokens",
        existing_type=sa.NUMERIC(precision=9, scale=4),
        type_=sa.Numeric(precision=9, scale=6),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "price",
        existing_type=sa.NUMERIC(precision=9, scale=4),
        type_=sa.Numeric(precision=9, scale=6),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "price",
        existing_type=sa.Numeric(precision=9, scale=6),
        type_=sa.NUMERIC(precision=9, scale=4),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "tokens",
        existing_type=sa.Numeric(precision=9, scale=6),
        type_=sa.NUMERIC(precision=9, scale=4),
        existing_nullable=True,
    )
    op.drop_column("users", "total_price")
    # ### end Alembic commands ###
