"""number not uniuqe

Revision ID: ab07bb77af38
Revises: 1f3f451eeb64
Create Date: 2023-06-23 02:43:44.052429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ab07bb77af38"
down_revision = "1f3f451eeb64"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "admins", ["id"])
    op.drop_constraint("users_phone_number_key", "users", type_="unique")
    op.create_unique_constraint(None, "users", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.create_unique_constraint("users_phone_number_key", "users", ["phone_number"])
    op.drop_constraint(None, "admins", type_="unique")
    # ### end Alembic commands ###
