"""remove defult on admin_id

Revision ID: b926f1356a75
Revises: abb025afdecc
Create Date: 2023-06-23 17:12:45.940036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b926f1356a75'
down_revision = 'abb025afdecc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
