"""init-migration

Revision ID: d6eb8452ec59
Revises: 
Create Date: 2023-05-24 13:40:42.104941

"""
from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision = "d6eb8452ec59"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin",
        sa.Column("id", app.utils.types.GUID(), nullable=False),
        sa.Column("admin_email", sa.String(), nullable=False),
        sa.Column("admin_username", sa.String(), nullable=True),
        sa.Column("admin_password", sa.String(), nullable=True),
        sa.Column("admin_price", sa.Numeric(precision=9, scale=4), nullable=True),
        sa.Column("private_key", sa.LargeBinary(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("admin_email"),
        sa.UniqueConstraint("admin_username", "admin_price"),
    )
    op.create_table(
        "users",
        sa.Column("id", app.utils.types.GUID(), nullable=False),
        sa.Column("_uuid", app.utils.types.GUID(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("tokens", sa.Numeric(precision=9, scale=4), nullable=True),
        sa.Column("price", sa.Numeric(precision=9, scale=4), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("_uuid"),
        sa.UniqueConstraint("email"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_table("admin")
    # ### end Alembic commands ###
