version: '3'

services:

# -----------------------
# API service for fastapi
# -----------------------
  api:
    image: wasata/api
    restart: unless-stopped
    container_name: wasata_api
    profiles: ["production", "dev", "demo"]
    ports:
      - ${WASATA_PORT}:${WASATA_PORT}
    command: "./entrypoint.sh"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://api:8080/health"]
      interval: 15s
      retries: 5
    depends_on:
      - dev-postgres
    networks:
      - wasata-bridge

# -------------------------
# Postgres database service
# -------------------------
  dev-postgres:
    image: wasata/dev-postgres
    restart: unless-stopped
    container_name: wasata_db
    profiles: ["demo", "dev"]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 30s
      timeout: 60s
      retries: 5
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - wasata-bridge

# -------------------------
# Frontend service
# -------------------------
  frontend:
    container_name: wasata_frontend
    image: wasata/frontend
    profiles: ["production", "dev", "demo"]
    restart: unless-stopped
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    command: npm start
    depends_on:
      - api
    networks:
      - wasata-bridge

# --------------------------------
# PgAdmin database browser service
# --------------------------------
  pgadmin:
    container_name: wasata_pgadmin
    image: dpage/pgadmin4
    platform: linux/amd64
    profiles: ["production", "demo"]
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - ${PGADMIN_PORT}:${PGADMIN_PORT}
    restart: unless-stopped
    depends_on:
      - dev-postgres
    networks:
      - wasata-bridge

# ----------------------------
# Container log viewer service
# ----------------------------
  dozzle:
    container_name: wasata_dozzle
    image: amir20/dozzle:latest
    platform: linux/amd64
    profiles: ["production", "demo"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080
    depends_on:
      - dev-postgres

# bridge network for all containers
networks:
  wasata-bridge:
    driver: bridge
